# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_dosage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dosage',
            field=models.PositiveIntegerField(choices=[(1, 'Tablet'), (2, 'Capsule'), (3, 'Suppository'), (4, 'Syrup'), (5, 'Suspension'), (6, 'Injection (IV)'), (7, 'Injection (IM)'), (8, 'Contraceptive'), (9, 'Sanitary Napkin')], default=1),
        ),
    ]
