# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20160814_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='power',
            field=models.CharField(default='', max_length=50),
        ),
    ]
