# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20160814_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='dosage',
            field=models.PositiveIntegerField(choices=[(1, 'Tablet'), (2, 'Capsule'), (3, 'Suppository'), (4, 'Syrup'), (5, 'Suspension'), (6, 'Injection (IV)'), (7, 'Injection (IM)'), (8, 'Contraceptive'), (9, 'Sanitary Napkin'), (10, 'Cream'), (11, 'Ointment')], default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='Unique value for product page URL, created from name.', max_length=255, unique=True),
        ),
    ]
