# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20160824_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Deselect this instead of deleting the product.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='Unique identifier for the product', max_length=50),
        ),
    ]
