# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-19 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20160919_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='piece', help_text='Unit used to sell the product, e.g. 250 gm, bottle, etc.', max_length=20),
        ),
    ]
