# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20160924_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='power',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
