# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-06 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, height_field=b'height', upload_to=b'img/items', width_field=b'width'),
        ),
        migrations.AlterField(
            model_name='product',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_product_related_+', to='catalog.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, height_field=b'height', upload_to=b'img/items', width_field=b'width'),
        ),
    ]
