# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-07 04:45
from __future__ import unicode_literals

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20161006_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.SubCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, height_field=b'height', upload_to=catalog.models.UploadToPathAndRename(b'img/items'), width_field=b'width'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, height_field=b'height', upload_to=catalog.models.UploadToPathAndRename(b'img/items'), width_field=b'width'),
        ),
    ]
