# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-12 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20161012_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dosage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Dosage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.SubCategory'),
        ),
    ]
