# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-12 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20161012_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='power',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default=b'Piece', help_text=b'Unit used to sell the product, e.g. 250 gm, bottle, etc.', max_length=20),
        ),
    ]
