# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-31 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20161022_0711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='old_price',
            new_name='discount_price',
        ),
    ]
