# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-05 06:39
from __future__ import unicode_literals

import catalog.models
import catalog.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_auto_20161231_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, height_field=b'height', storage=catalog.storage.OverwriteStorage(), upload_to=catalog.models.UploadToPathAndRename(b'img/items'), width_field=b'width'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, height_field=b'height', storage=catalog.storage.OverwriteStorage(), upload_to=catalog.models.UploadToPathAndRenameThumbnail(b'img/items'), width_field=b'width'),
        ),
    ]
