# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-05-23 13:34
from __future__ import unicode_literals

import catalog.models
import catalog.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_auto_20170105_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Unique value for product page URL, created from name.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, height_field='height', storage=catalog.storage.OverwriteStorage(), upload_to=catalog.models.UploadToPathAndRename('img/items'), width_field='width'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='Unique value for product page URL, created from name.', max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, height_field='height', storage=catalog.storage.OverwriteStorage(), upload_to=catalog.models.UploadToPathAndRenameThumbnail('img/items'), width_field='width'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='Piece', help_text='Unit used to sell the product, e.g. 250 gm, bottle, etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(help_text='Unique value for product page URL, created from name.', max_length=255, unique=True),
        ),
    ]
