# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20160809_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestedproduct',
            name='country',
        ),
        migrations.RemoveField(
            model_name='requestedproduct',
            name='group',
        ),
        migrations.RemoveField(
            model_name='requestedproduct',
            name='name',
        ),
        migrations.RemoveField(
            model_name='requestedproduct',
            name='power',
        ),
        migrations.RemoveField(
            model_name='requestedproduct',
            name='quantity',
        ),
    ]
