# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='thumbnail',
            field=models.ImageField(blank=True, height_field='height', upload_to='uploads/prescription', width_field='width'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='height',
            field=models.PositiveIntegerField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='image',
            field=models.ImageField(blank=True, height_field=models.PositiveIntegerField(blank=True, max_length=4), max_length=255, upload_to='uploads/prescription', width_field=models.PositiveIntegerField(blank=True, max_length=4)),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='width',
            field=models.PositiveIntegerField(blank=True, max_length=4),
        ),
    ]
