# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20160810_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='height',
            field=models.PositiveIntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='image',
            field=models.ImageField(blank=True, height_field=models.PositiveIntegerField(blank=True, max_length=4, null=True), max_length=255, upload_to='uploads/prescription', width_field=models.PositiveIntegerField(blank=True, max_length=4, null=True)),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='width',
            field=models.PositiveIntegerField(blank=True, max_length=4, null=True),
        ),
    ]
