# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20160810_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
