# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20160811_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='image',
            field=models.ImageField(height_field='height', upload_to='static/img/uploads/prescription', width_field='width'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='thumbnail',
            field=models.ImageField(height_field='height', upload_to='static/img/uploads/prescription', width_field='width'),
        ),
    ]
