# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-24 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20160811_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='thumbnail',
            field=models.ImageField(upload_to='static/img/uploads/prescription'),
        ),
    ]
