# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20160824_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
