# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-18 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20160825_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='image',
            field=models.ImageField(height_field='height', upload_to='img/uploads/prescription', width_field='width'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='thumbnail',
            field=models.ImageField(upload_to='img/uploads/prescription'),
        ),
    ]
