# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-05 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20161006_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedproduct',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestedproduct',
            name='status',
            field=models.SmallIntegerField(choices=[(1, b'Requested'), (2, b'Processing'), (3, b'Delivered')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.IntegerField(choices=[(1, b'10AM - 12PM'), (2, b'12PM - 2PM'), (3, b'2PM - 4PM'), (4, b'4PM - 6PM'), (5, b'6PM - 8PM'), (6, b'8PM - 10PM')], default=4),
        ),
    ]
