# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-05 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_auto_20170105_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedproduct',
            name='note',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
