# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-06 05:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20170105_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.CharField(default=datetime.datetime(2017, 1, 6, 5, 42, 40, 494723), max_length=50),
            preserve_default=False,
        ),
    ]
