# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-05-23 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.IntegerField(choices=[(1, '10AM - 12PM'), (2, '12PM - 2PM'), (3, '2PM - 4PM'), (4, '4PM - 6PM'), (5, '6PM - 8PM'), (6, '8PM - 10PM')], default=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Submitted'), (2, 'Processed'), (3, 'Shipped'), (4, 'Cancelled'), (5, 'Returned')], default=1),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='image',
            field=models.ImageField(height_field='height', upload_to='img/prescription', width_field='width'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='thumbnail',
            field=models.ImageField(upload_to='img/prescription'),
        ),
        migrations.AlterField(
            model_name='requestedproduct',
            name='note',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='requestedproduct',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Requested'), (2, 'Processing'), (3, 'Delivered')], default=1),
        ),
    ]
